import HeroSection from "./componenets/HeroSection";
import FooterSection from "./componenets/FooterSection";
import StoresSection from "./componenets/StoresSection";
import Partner from "./componenets/Partner";
import Testimonials from "./componenets/Testimonials";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Fast Food",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main>
      <HeroSection />
      <StoresSection />
      <Testimonials />
      <Partner />
      <FooterSection />
    </main>
  );
}
